/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 camera.glb 
Author: DavidKlein (https://sketchfab.com/DavidKlein)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/hasselblad-500cm-highpoly-0df63dfc1f594be9aa2b91f91f509ed1
Title: Hasselblad 500C/M (highpoly)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/camera.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 8.382, -3.938]}>
          <mesh
            geometry={nodes.Body002_body_0.geometry}
            material={materials.body}
          />
          <mesh
            geometry={nodes.Body002_body_0_1.geometry}
            material={materials.body}
          />
          <mesh
            geometry={nodes.Body002_body_0_2.geometry}
            material={materials.body}
          />
        </group>
        <group position={[0, 8.382, -3.938]}>
          <mesh
            geometry={nodes.ViewFInder001_ViewFidner_0.geometry}
            material={materials.ViewFidner}
          />
          <mesh
            geometry={nodes.ViewFInder001_ViewFidner_0_1.geometry}
            material={materials.ViewFidner}
          />
        </group>
        <group position={[0, 8.382, -3.938]}>
          <mesh
            geometry={nodes.Knopjes001_Knopjes_0.geometry}
            material={materials.Knopjes}
          />
          <mesh
            geometry={nodes.Knopjes001_Knopjes_0_1.geometry}
            material={materials.Knopjes}
          />
        </group>
        <mesh
          geometry={nodes.Lens002_Lens_0.geometry}
          material={materials.Lens}
          position={[0, 8.382, -3.938]}
        />
        <mesh
          geometry={nodes.MidPoly_rings_02_Lens_0.geometry}
          material={materials.Lens}
          position={[0, 8.382, -3.938]}
        />
        <mesh
          geometry={nodes.Logo_Plates_Extras_LOgo_0.geometry}
          material={materials.Extras_LOgo}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/camera.glb");
