/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 camera2.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

const Model = React.forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("/models/camera2.glb");
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["black 2"]}
        position={[-0.165, 3.673, -0.369]}
        rotation={[-1.395, 0.061, 2.373]}
        scale={118.19}
      />
      <group
        position={[0.407, 5.82, 0.439]}
        rotation={[0.117, -0.767, 3.057]}
        scale={118.19}
      >
        <mesh
          geometry={nodes.Cylinder004_1.geometry}
          material={materials["black 2"]}
        />
        <mesh
          geometry={nodes.Cylinder004_2.geometry}
          material={materials.silver}
        />
      </group>
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials["black 2"]}
        position={[-0.101, 5.035, -0.147]}
        rotation={[-1.395, 0.061, 2.373]}
        scale={[118.19, 126.876, 118.19]}
      />
      <group
        position={[-0.734, 5.868, -0.68]}
        rotation={[0.117, -0.767, 3.057]}
        scale={[93.633, 93.633, 110.199]}
      >
        <mesh
          geometry={nodes.Cylinder023_1.geometry}
          material={materials["black 2"]}
        />
        <mesh
          geometry={nodes.Cylinder023_2.geometry}
          material={materials.silver}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder024.geometry}
        material={materials.orange}
        position={[0.835, 3.472, 0.551]}
        rotation={[0.239, 0.8, -1.658]}
        scale={118.19}
      />
      <mesh
        geometry={nodes.Cylinder025.geometry}
        material={materials.Material}
        position={[1.012, 3.446, 0.714]}
        rotation={[0.239, 0.8, -1.658]}
        scale={[142.242, 142.242, 118.19]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials["black 2"]}
        position={[1.805, 3.323, 1.331]}
        rotation={[0.239, 0.8, -1.658]}
        scale={111.966}
      />
      <mesh
        geometry={nodes.Cylinder026.geometry}
        material={materials.orange}
        position={[-0.536, 5.003, -0.126]}
        rotation={[0.117, -0.767, -0.085]}
        scale={15.382}
      />
      <mesh
        geometry={nodes.Cylinder027.geometry}
        material={materials.orange}
        position={[-0.383, 4.968, 0.018]}
        rotation={[0.117, -0.767, -0.085]}
        scale={15.382}
      />
      <mesh
        geometry={nodes.Cylinder028.geometry}
        material={materials.orange}
        position={[-0.235, 4.934, 0.158]}
        rotation={[0.117, -0.767, -0.085]}
        scale={15.382}
      />
      <mesh
        geometry={nodes.Cube035.geometry}
        material={materials["black 2"]}
        position={[-0.956, 3.943, -1.19]}
        rotation={[0.239, 0.8, -1.658]}
        scale={118.19}
      />
      <group
        position={[-1.299, 4.019, -1.514]}
        rotation={[-2.878, -0.798, -1.466]}
        scale={113.267}
      >
        <mesh
          geometry={nodes.Cylinder029_1.geometry}
          material={materials["black 2"]}
        />
        <mesh
          geometry={nodes.Cylinder029_2.geometry}
          material={materials.orange}
        />
      </group>
      <mesh
        geometry={nodes.Cube036.geometry}
        material={materials.orange}
        position={[-1.094, 3.656, 0.09]}
        rotation={[-1.395, 0.061, -0.769]}
        scale={118.19}
      />
      <mesh
        geometry={nodes.Cube037.geometry}
        material={materials["blue "]}
        position={[-0.396, 3.497, 0.813]}
        rotation={[-1.395, 0.061, -0.769]}
        scale={118.19}
      />
      <mesh
        geometry={nodes.Cylinder030.geometry}
        material={materials.silver}
        position={[-0.418, 3.732, 0.888]}
        rotation={[0.117, -0.767, -0.085]}
        scale={[56.293, 56.293, 45.111]}
      />
      <mesh
        geometry={nodes.Cylinder031.geometry}
        material={materials.silver}
        position={[-0.433, 3.488, 0.845]}
        rotation={[0.117, -0.767, -0.085]}
        scale={[56.293, 56.293, 45.111]}
      />
      <mesh
        geometry={nodes.Cylinder032.geometry}
        material={materials.silver}
        position={[-0.447, 3.257, 0.804]}
        rotation={[0.117, -0.767, -0.085]}
        scale={[56.293, 56.293, 45.111]}
      />
      <mesh
        geometry={nodes.Cube038.geometry}
        material={materials["orange 3"]}
        position={[-1.16, 3.648, 0.159]}
        rotation={[-1.395, 0.061, -0.769]}
        scale={80.253}
      />
      <mesh
        geometry={nodes.Cylinder033.geometry}
        material={materials.silver}
        position={[-1.353, 3.871, 0.118]}
        rotation={[-3.024, 0.767, 0.085]}
        scale={78.061}
      />
      <mesh
        geometry={nodes.Cylinder034.geometry}
        material={materials.silver}
        position={[-1.052, 3.801, 0.402]}
        rotation={[-3.024, 0.767, 0.085]}
        scale={78.061}
      />
      <mesh
        geometry={nodes.Cylinder035.geometry}
        material={materials.silver}
        position={[-1.378, 3.467, 0.046]}
        rotation={[-3.024, 0.767, 0.085]}
        scale={78.061}
      />
      <mesh
        geometry={nodes.Cylinder036.geometry}
        material={materials.silver}
        position={[-1.077, 3.398, 0.33]}
        rotation={[-3.024, 0.767, 0.085]}
        scale={78.061}
      />
      <mesh
        geometry={nodes.Cube039.geometry}
        material={materials.silver}
        position={[-0.275, 2.289, -0.56]}
        rotation={[-1.395, 0.061, -0.769]}
        scale={118.19}
      />
      <mesh
        geometry={nodes.Cylinder037.geometry}
        material={materials["black 2"]}
        position={[-0.272, 2.299, -0.569]}
        rotation={[-1.395, 0.061, -0.769]}
        scale={118.19}
      />
      <mesh
        geometry={nodes.Cube040.geometry}
        material={materials.Material}
        position={[-0.336, 1.042, -0.807]}
        rotation={[-1.395, 0.061, -0.769]}
        scale={118.19}
      />
      <mesh
        geometry={nodes.Sphere005.geometry}
        material={materials.kaca}
        position={[2.18, 3.236, 1.699]}
        rotation={[0.239, 0.8, -1.658]}
        scale={113.38}
      />
    </group>
  );
});

// Ajout du display name pour ESLint
Model.displayName = "Model";

export default Model;

useGLTF.preload("/models/camera2.glb");
