/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 green-screend.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

const Model = React.forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("/models/green-screend.glb");
  return (
    <group ref={ref} {...props} dispose={null}>
      <group
        position={[-2.217, 3.146, 0.321]}
        rotation={[-Math.PI / 2, 0, 0.15]}
        scale={89.955}
      >
        <mesh
          geometry={nodes.Cylinder044_1.geometry}
          material={materials["black 2"]}
        />
        <mesh
          geometry={nodes.Cylinder044_2.geometry}
          material={materials.orange}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder045.geometry}
        material={materials["black 2"]}
        position={[-1.733, 1.716, 0.248]}
        rotation={[-1.483, -0.524, 0.173]}
        scale={89.955}
      />
      <mesh
        geometry={nodes.Cylinder046.geometry}
        material={materials["black 2"]}
        position={[-2.757, 1.716, 0.403]}
        rotation={[-1.658, 0.524, -2.968]}
        scale={89.955}
      />
      <mesh
        geometry={nodes.Cylinder047.geometry}
        material={materials["black 2"]}
        position={[-2.14, 1.716, 0.834]}
        rotation={[-2.096, -0.076, -1.441]}
        scale={89.955}
      />
      <mesh
        geometry={nodes.Cylinder048.geometry}
        material={materials["black 2"]}
        position={[-2.295, 1.716, -0.191]}
        rotation={[-1.046, 0.076, 1.7]}
        scale={89.955}
      />
      <mesh
        geometry={nodes.Cylinder049.geometry}
        material={materials.silver}
        position={[-2.734, 2.31, 0.399]}
        rotation={[-Math.PI, 1.421, 1.571]}
        scale={24.717}
      />
      <group
        position={[2.034, 3.146, -0.321]}
        rotation={[-Math.PI / 2, 0, -2.992]}
        scale={89.955}
      >
        <mesh
          geometry={nodes.Cylinder050_1.geometry}
          material={materials["black 2"]}
        />
        <mesh
          geometry={nodes.Cylinder050_2.geometry}
          material={materials.orange}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder051.geometry}
        material={materials["black 2"]}
        position={[1.55, 1.716, -0.248]}
        rotation={[-1.658, 0.524, -2.968]}
        scale={89.955}
      />
      <mesh
        geometry={nodes.Cylinder052.geometry}
        material={materials["black 2"]}
        position={[2.574, 1.716, -0.403]}
        rotation={[-1.483, -0.524, 0.173]}
        scale={89.955}
      />
      <mesh
        geometry={nodes.Cylinder053.geometry}
        material={materials["black 2"]}
        position={[1.957, 1.716, -0.834]}
        rotation={[-1.046, 0.076, 1.7]}
        scale={89.955}
      />
      <mesh
        geometry={nodes.Cylinder054.geometry}
        material={materials["black 2"]}
        position={[2.112, 1.716, 0.191]}
        rotation={[-2.096, -0.076, -1.441]}
        scale={89.955}
      />
      <mesh
        geometry={nodes.Cylinder055.geometry}
        material={materials.silver}
        position={[2.551, 2.31, -0.399]}
        rotation={[0, -1.421, -1.571]}
        scale={24.717}
      />
      <group
        position={[-0.13, 5.732, 0.006]}
        rotation={[0, -1.421, 1.571]}
        scale={109.267}
      >
        <mesh
          geometry={nodes.Cylinder056_1.geometry}
          material={materials["black 2"]}
        />
        <mesh
          geometry={nodes.Cylinder056_2.geometry}
          material={materials.orange}
        />
      </group>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["orange 3.001"]}
        position={[0.023, 4.211, 0.088]}
        rotation={[-Math.PI / 2, 0, 0.15]}
        scale={109.267}
      />
    </group>
  );
});

// Ajout du display name pour ESLint
Model.displayName = "Model";

export default Model;

useGLTF.preload("/models/green-screend.glb");
