/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 story-board.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

const Model = React.forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("/models/story-board.glb ");
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["black 2"]}
        position={[-0.236, 3.779, 0.112]}
        rotation={[-1.671, -0.027, 0.157]}
        scale={117.509}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials.orange}
        position={[-0.172, 3.821, 0.512]}
        rotation={[-1.671, -0.027, 0.157]}
        scale={117.509}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials["orange 3"]}
        position={[-0.128, 4.795, 0.518]}
        rotation={[-1.671, -0.027, 0.157]}
        scale={117.509}
      />
      <mesh
        geometry={nodes.Cube035.geometry}
        material={materials.white}
        position={[-0.514, 4.833, 0.774]}
        rotation={[-1.671, -0.027, 0.157]}
        scale={[86.18, 71.936, 86.18]}
      />
      <mesh
        geometry={nodes.Cube036.geometry}
        material={materials.white}
        position={[0.377, 4.852, 0.722]}
        rotation={[-1.671, -0.027, 0.157]}
        scale={[86.18, 71.936, 86.18]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials.white}
        position={[-0.088, 5.624, 0.745]}
        rotation={[3.037, -0.157, -0.028]}
        scale={29.492}
      />
      <mesh
        geometry={nodes.Cube037.geometry}
        material={materials.white}
        position={[-0.309, 3.081, 0.775]}
        rotation={[-1.671, -0.027, 0.157]}
        scale={97.966}
      />
      <mesh
        geometry={nodes.Cube038.geometry}
        material={materials.white}
        position={[-0.294, 2.568, 0.826]}
        rotation={[-1.671, -0.027, 0.157]}
        scale={97.966}
      />
      <mesh
        geometry={nodes.Cube039.geometry}
        material={materials.white}
        position={[-0.281, 2.063, 0.877]}
        rotation={[-1.671, -0.027, 0.157]}
        scale={97.966}
      />
      <group
        position={[2.045, 3.773, 0.711]}
        rotation={[-1.736, 0.418, -0.691]}
        scale={87.238}
      >
        <mesh
          geometry={nodes.Cylinder008_1.geometry}
          material={materials.orange}
        />
        <mesh
          geometry={nodes.Cylinder008_2.geometry}
          material={materials["orange 3"]}
        />
        <mesh
          geometry={nodes.Cylinder008_3.geometry}
          material={materials.silver}
        />
      </group>
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials.silver}
        position={[2.673, 4.332, 0.902]}
        rotation={[0.291, 0.782, -2.18]}
        scale={[87.238, 87.238, 87.239]}
      />
    </group>
  );
});

// Ajout du display name pour ESLint
Model.displayName = "Model";

export default Model;

useGLTF.preload("/models/story-board.glb ");
