/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 studio.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/studio.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["Floor_and_wall_floor&wall_0"].geometry}
        material={materials.floorwall}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1422.507}
      />
      <mesh
        geometry={nodes.floodlight_floodlight001_0.geometry}
        material={materials["floodlight.001"]}
        position={[938.631, 659.142, -674.104]}
        rotation={[-Math.PI / 2, 0, -0.08]}
        scale={100}
      />
      <mesh
        geometry={nodes.floodlight001_floodlight_0.geometry}
        material={materials.floodlight}
        position={[-223.531, 659.142, 767.378]}
        rotation={[-Math.PI / 2, 0, -1.267]}
        scale={100}
      />
      <mesh
        geometry={nodes.chair_chair002_0.geometry}
        material={materials["chair.002"]}
        position={[1299.474, 399.217, 89.246]}
        rotation={[Math.PI, -1.247, Math.PI]}
        scale={[7.782, 138.423, 7.782]}
      />
      <mesh
        geometry={nodes.chair1_chair_0.geometry}
        material={materials.chair}
        position={[-644.988, 399.217, 1277.737]}
        rotation={[Math.PI, 0.046, -Math.PI]}
        scale={[7.782, 138.423, 7.782]}
      />
      <mesh
        geometry={nodes.chair2_chair001_0.geometry}
        material={materials["chair.001"]}
        position={[1344.606, 399.217, -369.602]}
        rotation={[Math.PI, -1.487, Math.PI]}
        scale={[7.782, 138.423, 7.782]}
      />
      <mesh
        geometry={nodes.camera_camera_0.geometry}
        material={materials.camera}
        position={[828.635, 649.984, 749.202]}
        rotation={[-Math.PI / 2, 0, -0.778]}
        scale={[125.835, 52.776, 85.815]}
      />
    </group>
  );
}

useGLTF.preload("/models/studio.glb");
